### ISSUE TITLE
worker_state does not work across map calls

### ISSUE THREAD

**Issue by remondn-swk** [Slimmer-AI/mpire#15]
I wrote the following example :

```python
from mpire import WorkerPool


def set_state(worker_state, x):
    worker_state["x"] = x


def get_state(worker_state, x):
    return worker_state["x"] * x


if __name__ == "__main__":
    pool = WorkerPool(n_jobs=3, use_worker_state=True, keep_alive=True)

    pool.map(set_state, [1, 2, 4])

    results = pool.map(get_state, [2, 2, 2])

    print(results)

    pool.stop_and_join()
```

Expected result :

> [2, 4, 8]

---

But instead I'm having an error : 

```
KeyError: '\n\nException occurred in Worker-0 with the following arguments:\nArg 0: 2\nTraceback (most recent call last):\n  File "C:\\Users\\Nicolas\\AppData\\Roaming\\Python\\Python39\\site-packages\\mpire\\worker.py", line 301, in _run_safely\n    results = func()\n  File "C:\\Users\\Nicolas\\AppData\\Roaming\\Python\\Python39\\site-packages\\mpire\\worker.py", line 255, in _func\n    results = func(args)\n  File "C:\\Users\\Nicolas\\AppData\\Roaming\\Python\\Python39\\site-packages\\mpire\\worker.py", line 394, in _helper_func_with_idx\n    return args[0], self._call_func(func, args[1])\n  File "C:\\Users\\Nicolas\\AppData\\Roaming\\Python\\Python39\\site-packages\\mpire\\worker.py", line 421, in _call_func\n    return func(args)\n  File "C:\\Users\\Nicolas\\Documents\\workspace\\poubelle\\lolilol.py", line 9, in get_state\n    return worker_state["x"] * x\nKeyError: \'x\'\n'
```

It seems worker states are not kept across `map()` calls. Is it expected behavior ? How can I modify my script to have the expected result ?

**Comment by sybrenjansen** [comment]
Unfortunately, right now, workers are restarted whenever the function you want to parallelize changes. This is documented in the first paragraph of https://slimmer-ai.github.io/mpire/usage/worker_pool.html#keep-alive.If you would call `pool.map(set_state)` twice, you would see that the state is kept. 

Keeping the workers alive when the function changes is something I want to implement in the coming few weeks. It shouldn't be that hard to add.

**Comment by remondn-swk** [comment]
Thanks for your fast answer !

That would be a great enhancement :)

**Comment by sybrenjansen** [comment]
v2.3.0 has been released and enables reusing workers even though the function changes!
