### ISSUE TITLE
TypeError at tqdm_utils

### ISSUE THREAD

**Issue by pemm8** [Slimmer-AI/mpire#23]
Hi there,

I'm getting an issue when setting `progress_bar = True`.

Traceback:

```
Traceback (most recent call last):
  File "/Users/user/Projects/project/hk_analysis/matching.py", line 74, in <module>
    process_matches_multi()
  File "/Users/user/Projects/project/hk_analysis/matching.py", line 49, in process_matches_multi
    matching_results = pool.map(atomic_matching, [{'item': item} for item in updated[:10]], progress_bar=True)
  File "/Users/user/.virtualenvs/pdf_analysis/lib/python3.9/site-packages/mpire/pool.py", line 265, in map
    results = self.map_unordered(func, ((args_idx, args) for args_idx, args in enumerate(iterable_of_args)),
  File "/Users/user/.virtualenvs/pdf_analysis/lib/python3.9/site-packages/mpire/pool.py", line 324, in map_unordered
    return list(self.imap_unordered(func, iterable_of_args, iterable_len, max_tasks_active, chunk_size,
  File "/Users/user/.virtualenvs/pdf_analysis/lib/python3.9/site-packages/mpire/pool.py", line 490, in imap_unordered
    tqdm_manager_owner = TqdmManager.start_manager() if progress_bar else False
  File "/Users/user/.virtualenvs/pdf_analysis/lib/python3.9/site-packages/mpire/tqdm_utils.py", line 121, in start_manager
    cls.MANAGER_HOST.value = cls.MANAGER.address[1:]
  File "<string>", line 11, in setvalue
TypeError: bytes expected instead of str instance
```
Snapshot of code:

```
from mpire import WorkerPool
from mpire.dashboard import connect_to_dashboard

connect_to_dashboard(8080)

def atomic_matching(shared_objects, item):
    ### ... match processing
    return data

def process_matches_multi():
    ### ... get data
    ### ... set choices and previous

    with WorkerPool(n_jobs=5) as pool:
        pool.set_shared_objects((choices, previous))
        matching_results = pool.map(atomic_matching, [{'item': item} for item in updated])
    
    ### ... output results
```

If I change tqdm_utils as follows (line 121), it disappears but no progress bar appears and the dashboard does not connect

```
cls.MANAGER_HOST.value = cls.MANAGER.address[1:].encode()
```

I've checked tqdm and it is working in isolation.

Versions are:
`mpire==2.3.0`
`tqdm==4.62.1` (Also tried tqdm==4.62.3)
`Python 3.9.7`

Love the project and thanks for all the hard work :)

Many thanks,
Paul

**Comment by vlomshakov** [comment]
Hey! I've faced the problem too under Mac OS with python version 3.9.7.
With another setups (windows and ubuntu with python 3.7.6) everything works perfect.

**Comment by sybrenjansen** [comment]
Ok, thnx for letting me know. I'm a bit busy at the moment, but I'll get it to it soon

**Comment by sybrenjansen** [comment]
@pemm8 , @vlomshakov  can anyone of you check if the linked PR fixes your issues?

**Comment by vlomshakov** [comment]
@sybrenjansen thanks! Everything works now (with 2.3.1 version).
