### ISSUE TITLE
Appears incompatible with Windows

### ISSUE THREAD

**Issue by Cyb3r-Jak3** [Slimmer-AI/mpire#6]
`mprie` appears to be incompatible with Windows. When attempting to import, just running `python -c "from mpire import WorkerPool"` I get:

```powershell
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "F:\git\dectector\venv\lib\site-packages\mpire\__init__.py", line 4, in <module>
    from mpire.pool import WorkerPool
  File "F:\git\dectector\venv\lib\site-packages\mpire\pool.py", line 17, in <module>
    from mpire.comms import WorkerComms
  File "F:\git\dectector\venv\lib\site-packages\mpire\comms.py", line 8, in <module>
    from mpire.context import MP_CONTEXTS
  File "F:\git\dectector\venv\lib\site-packages\mpire\context.py", line 25, in <module>
    MP_CONTEXTS = {'mp': {'fork': mp.get_context('fork'),
  File "F:\Program Files\Python38\lib\multiprocessing\context.py", line 239, in get_context
    return super().get_context(method)
  File "F:\Program Files\Python38\lib\multiprocessing\context.py", line 193, in get_context
    raise ValueError('cannot find context for %r' % method) from None
ValueError: cannot find context for 'fork'
```
Using [Windows Subsystem for Linux (WSL](https://docs.microsoft.com/en-us/windows/wsl/install-win10) there are no issues. Searching around I found this issue https://github.com/nalepae/pandarallel/issues/109 and this project says only WSL, Mac or 
Linux is supported. Might be worth adding something to the ReadMe

**Comment by sybrenjansen** [comment]
Windows support is now available!

**Comment by ZorkJ** [comment]
Hello, again I came across the problem in windows: 

ValueError: cannot find context for 'fork'
